name: CI/CD Laravel + Docker

on:
  push:
    branches:
      - seck_amadou_burger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code depuis GitHub
        uses: actions/checkout@v3

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Installer les dépendances Laravel
        run: composer install --no-dev --optimize-autoloader

      - name: Copier le fichier .env
        run: cp .env.example .env

      - name: Generer la cle de lapplication
        run: php artisan key:generate
